### ISSUE TITLE
Undefined values get escaped as "undefined"

### ISSUE THREAD

**Issue by DanaIv** [component/escape-html#24]
The source of the issue seems to be: https://github.com/component/escape-html/blob/master/index.js#L34

Could this be changed to first check if the input is undefined and then turn it into a string? I am asking because I would like to automatically escape properties in an object without worrying whether they are undefined or not.

**Comment by dougwilson** [comment]
Hi @DanaIv yea, there are certainly many different ways people may want to handle `undefined`, `null`, `{}`, or many other things. Since this module was only designed to take a string, we decided that it should act like other base JavaScript built-ins that take strings: call `ToStirng` internal on the incoming variable. This turns `undefined` to `"undefined"`, for example.

You can see this same behavior in most all of the JavaScript built-ins, for example `RegExp.prototype.test`: `console.log(/undefined/.test(undefined))` prints `true` since it turned that into the string `"undefined"`.

It's impossible to really understand who is relying on our behavior here, so any change would be a major, but without any real desire save for this single issue, we'll likely be forcing many, many people to change their code.

I would recommend just putting the check prior to calling this function. If you put the check prior, you can even skip calling this function all together, saving some performance of stack allocation, for example.

I hope that helps!
